### ISSUE TITLE
Need update to work with latest Rider

### ISSUE THREAD

**Issue by MikeKholomeev** [DenisPimenov/Rider-NegationHighlighter-Plugin#1]
"**Incompatible: equires IDE build 203.* or older**"
![Printscreen from settings](https://take.ms/HugzFN)

**Comment by DenisPimenov** [comment]
Sorry for delay. I uploaded new versions for 2021.1.3 and 2021.2EAP2. Within a couple of days they will be available

**Comment by DenisPimenov** [comment]
New plugin already available. Please reopen if there are problems with the new version
